### ISSUE TITLE
Netのインスタンス増えすぎかも?

### ISSUE THREAD

**Issue by aridai** [pumpkin1126/ami-gyo#22]
@pumpkin1126  Netを発射するごとにインスタンスが増えまくってるんだけど、これって画面から消えたら消すみたいな処理ってしてる?

**Comment by pumpkin1126** [comment]
消す処理を追加してなかったので、以下のコミットで消えるようにしました
a5bc34f

**Comment by aridai** [comment]
解決済みでしゅね。
