### ISSUE TITLE
魚の動き実装

### ISSUE THREAD

**Issue by pumpkin1126** [pumpkin1126/ami-gyo#27]
### 魚の動きについて
- 群れで行動する
- 回遊する
- 群れで離れながら大体同じところでとどまる
- 画面外から列で現れ、画面外へ抜ける
- 画面外から現れ、画面内で砂に隠れて死ぬ
- 画面内で砂から現れ、画面外へ離脱

とりあえず回遊から実装する
<br>重複可能なのは
- 回遊と群れ
のみ

**Comment by pumpkin1126** [comment]
楕円状の魚の回遊を実装

**Comment by aridai** [comment]
@pumpkin1126 #30 を実装したらこんな感じ?

- [x] 群れで行動する
- [x] 回遊する
- [ ] 群れで離れながら大体同じところでとどまる
- [ ] 画面外から列で現れ、画面外へ抜ける
- [ ] 画面外から現れ、画面内で砂に隠れて死ぬ
- [ ] 画面内で砂から現れ、画面外へ離脱

**Comment by pumpkin1126** [comment]
魚の動き実装完了しました。

### 変更点
作る動きのパターンは次のように変更しました
1. 回遊する（1周したら外へ抜ける）
2. 群れで回遊する（上と同じ）
3. ランダムな長さを直線的に動き、円を描くように180度以上ターンし、再度ランダムな方向へ...を繰り返す（何回かターンしたら外へ抜ける）
4. 上の動きを群れで行う

以上の4つです。他の動きは余裕があったら実装します

### 問題点
1. 4つ目の動きで、群れが離れ離れになることがある
2. 魚の発生頻度が高すぎるので、調整が必要

**Comment by pumpkin1126** [comment]
現在の状況
![image](https://user-images.githubusercontent.com/20056496/51244368-49927780-19c8-11e9-9aaf-3d734fb1d72c.png)
