### ISSUE TITLE
ゲーム画面の調整

### ISSUE THREAD

**Issue by pumpkin1126** [pumpkin1126/ami-gyo#32]
次の問題点を改善する
- ゲーム画面に魚が泳ぐフィールドの一部しか映っていない
- ゲーム画面に表示されるUIの位置が悪い
- アスペクト比が固定でないので、プラットフォームによってUIの位置がずれる

具体的には、現状では画像のようになってる
（真ん中の方に小さくUIが表示されている）
<img width="579" alt="default" src="https://user-images.githubusercontent.com/20056496/51245508-392fcc00-19cb-11e9-835c-e8ebb0641477.PNG">

**Comment by aridai** [comment]
#33 実装OK
