### ISSUE TITLE
群れの魚が震える問題の修正

### ISSUE THREAD

**Issue by pumpkin1126** [pumpkin1126/ami-gyo#37]
各魚について、次に進む方向を計算し、その結果を速度に直接代入しているので、魚が震えてしまう。
計算結果を加速度として与えることを検討したい。

**Comment by aridai** [comment]
# 実装方針
現在、魚が向いている方向は `IFishBehavior.GetVelocity()`が返す複数のベクトル の和の正規化ベクトルをそのまま実装している。  
これだと、反対向きのベクトルが一瞬だけ返ってきたときにピクピクする。  
だから、魚の向きの更新を間引く処理を検討している。

**Comment by aridai** [comment]
# 最終的な実装方針

#44 を参照。
簡単に言うと、変位ベクトルを方向ベクトルにした。
